### ISSUE TITLE
snip

### ISSUE THREAD

**Issue by t190058** [nc2020/2-t190058#2]
![image](https://user-images.githubusercontent.com/63434886/79523956-49d16500-809a-11ea-8b30-8d40f6a54103.png)

![image](https://user-images.githubusercontent.com/63434886/79524105-9c128600-809a-11ea-909c-ba19f5195787.png)
\int_{0}^{1} x=\frac{1}{2}

**Comment by junta-m** [comment]
dx が抜けています。修正してください。
